version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Check Python Version
          command: python --version

workflows:
  build_workflow:
    jobs:
      - build
